version = 0.1
[default.deploy.parameters]
stack_name = "nudedetector"
resolve_s3 = true
s3_prefix = "nudedetector"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
