org: ivanange
app: nudedetector
service: nudedetector

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  httpApi:
    cors: true
  ecr:
    images:
      appimage:
        path: ./
        platform: linux/amd64
  region: us-east-1
  memorySize: 3000

functions:
  api:
    image:
      name: appimage
    timeout: 360
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-wsgi
  - serverless-python-requirements

package:
  individually: true
  excludeDevDependencies: true
  exclude:
    - node_modules/**
    - features/**
    - venv/**
    - .git/**
